# Generated by Django 4.2.3 on 2023-09-01 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malaysia_app', '0002_zikr_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('iso3', models.TextField()),
                ('iso2', models.TextField()),
                ('numeric_code', models.IntegerField()),
                ('phone_code', models.TextField()),
                ('capital', models.TextField()),
                ('currency', models.TextField()),
                ('currency_name', models.TextField()),
                ('currency_symbol', models.TextField()),
                ('tld', models.TextField()),
                ('native', models.TextField()),
                ('region', models.TextField()),
                ('subregion', models.TextField()),
                ('nationality', models.TextField()),
                ('timezones', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('emoji', models.TextField()),
                ('emojiU', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='zikr_count',
            name='zikr_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 5, 3, 36, 180706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country_code', models.TextField()),
                ('country_name', models.TextField()),
                ('state_code', models.TextField()),
                ('type', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaysia_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('state_code', models.TextField()),
                ('state_name', models.TextField()),
                ('country_code', models.TextField()),
                ('country_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('wikiDataId', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaysia_app.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaysia_app.state')),
            ],
        ),
    ]
